---
title: "Vierdaagse"
author: "Joshua JOURDAM"
date: "2024-07-21"
categories: [news]
---

<https://www.4daagse.nl/en>
<https://www.vierdaagsefeesten.nl/en/>

The Vierdaagse, officially called the International Four Days Marches Nijmegen, is an annual multi-day walking event held in and around Nijmegen. It is one of the largest walking events in the world, attracting more than 45 000 participants. The Vierdaagse was first held in 1909 and has since grown into a large international event, with a festive atmosphere that includes concerts, parties, and celebrations in Nijmegen.

There is multiple key to participate to the event :

- Duration: The event lasts four days, during which participants walk a set distance each day.
- Distances: Participants can choose to walk 30 km, 40 km, or 50 km per day, depending on age, gender, and personal preference.
- When: It typically takes place in mid-July.
- Participants: The event attracts both military personnel and civilians. Military participants often walk in uniform and with gear, making it a distinctive feature of the event.
- Goal: The aim is to complete the four-day challenge and receive a Vierdaagse Cross (a medal awarded to those who finish successfully).

- military
- parachute
- bridge build

- vianen
- not so much people, the kilometere of the run have been reduced because of the heat

- bigbig party in nijmegen how many ? but i didn't went 