---
title: "BBQ ICT"
author: "Joshua JOURDAM"
date: "2024-08-04"
categories: [news]
---

I had the chance to experience something special this week: the annual ICT department BBQ. The mastermind behind this lively event was Dennis, our team leader, who crafted an invitation card and poster with a playful twist—“Chez le ROI ICT.” I could imagine that such a light-hearted joke might not fly as easily back in France, but here in the Netherlands, it was met with enthusiasm and laughter.

The BBQ brought together the three teams from our department: Innovation, Communication, and Technology. I met new people, it was quite easy, the Dutch are very direct which is really welcome as an intern.

We kicked off the festivities right after work at around 5 PM, and the fun continued well into the night, wrapping up around midnight. It was a perfect blend of delicious food, engaging conversation, and the kind of camaraderie that only comes from shared experiences.

Looking back, this BBQ was more than just a meal; it was a cultural experience that added a memorable highlight to my internship.
