---
title: "Daily routine"
author: "Joshua JOURDAM"
date: "2024-07-28"
categories: [news]
---

Now that it has been a few weeks since I started my internship, I have a good idea of what my daily routine looks like. I thought I would share it with you.

I usually start my day at 9am. I take the time to check my emails and to plan my day. Usually, I work on a single project, so I know what I have to do.  I usually work on a feature or a bug fix. I take the time to understand the requirements. Then, I start coding and finally before pushing my code, I test it.

The members team eats at any time after 12pm. We don't have a cafeteria in the office, so we stay at our desk. Here, this is not really a discussion time, everyone just eats on his side. On Friday we always order lunch from a restaurant nearby. Delivery services are very developed in the Netherlands, it's impressive. You can order anything at any time from a restaurant or a supermarket.

I leave the office around 5:30pm. Usually staff need to close the office at 6pm. It's weird from my perspective because in France, I used to leave the office around 7pm sometimes. But here, people come earlier and leave around 4:30pm. It's a cultural difference that I have to get used to. I think it's a good thing because it allows me to have a good work-life balance.

I usually go back to my accommodation directly after work. Sometimes we take aperitif with my host. Afterwards I chill out watching TV or playing video games. I also take the time to call my family and friends in France. I'm really happy to have found a good place to live. It's a bit far from the office, but it's a nice neighborhood. I'm really enjoying my time here in the Netherlands. I'm looking forward to discovering more about this country and its people.