---
title: "Development and project management"
author: "Joshua JOURDAM"
date: "2024-06-30"
categories: [news]
---

The team is responsible for developing and maintaining the softwares used by the company's employees. The softwares are used to manage the company's projects, to manage the maintenance of the installations and to manage the company's resources in addition to the Enterprise Resource Planning (ERP) features.

The team uses the Agile methodology to manage the development of the softwares. Each developer maintain it's own backlog and the team meets every end of the day to discuss the progress of the tasks and to plan the work for next day.

The team has a great CI/CD pipeline that allows to deploy the softwares quickly and safely. The team uses Azure DevOps to manage the source code and the pipelines.

All the applications are developed in C# with the .NET framework. The team uses the the ASP.NET framework with Blazor to develop the web applications.

> Project example : contact app
